name: Backend Docker Image CI

on:
  # push:
  #   branches: 
  #     - github-actions 
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:
    inputs:
      imagePath:
        description: 'Dockerfile Image Path'
        required: true
        default: 'backend'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
  
    
    - name: Docker Login
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_PAT }}

    - name: bashrun
      run: |
        echo ${{ github.event.inputs.imagePath }}
        ls -la ${{ github.event.inputs.imagePath }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ${{inputs.imagePath}}/Dockerfile
        push: true
        tags: |
          backend:latest
          backend:$(date +%s)
